openapi: 3.0.0
info:
  title: Numbers 
  version: '1.0'
tags:
  - name: Available Virtual Numbers
  - name: Active Virtual Numbers
paths:
  '/v1beta1/projects/{projectId}/activeNumbers':
    get:
      summary: List all your virtual numbers.
      description: Use this GET API to list all virtual numbers.
      operationId: NumberService_ListActiveNumbers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListActiveNumbersResponse'
        '400':
          description: 'pageToken, NumberPattern or orderBy is not valid'
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 400
                      message: ''
                      status: INVALID_ARGUMENT
                      details:
                        - type: BadRequest
                          fieldViolations:
                            - field: order_by
                              description: Invalid orderBy XXX
        default:
          description: An unexpected error has occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: regionCode
          description: '[country code](https://www.iso.org/obp/ui/#search) of the number.'
          in: query
          required: false
          schema:
            type: string
        - name: pattern
          description: Sequence of digits to search for.
          in: query
          required: false
          schema:
            type: string
        - name: searchPattern
          description: |-
            Search pattern to apply:
             - START: Numbers that start with the provided sequence of digits.
             - CONTAINS: Numbers that contain the sequence of digits.
             - END: Numbers that end with the sequence of digits.
          in: query
          required: false
          schema:
            type: string
            enum:
              - START
              - CONTAINS
              - END
        - name: type
          description: |-
            Filter by MOBILE, LOCAL or TOLL_FREE virtual number.
             - MOBILE: Numbers that belong to a specific range.
             - LOCAL: Numbers that are assigned to a specific geographic region.
             - TOLL_FREE: Number that is billed for all arriving calls.
          in: query
          required: false
          schema:
            type: string
            enum:
              - MOBILE
              - LOCAL
              - TOLL_FREE
            default: MOBILE
        - name: capability
          description: |-
            Filter by SMS and/or VOICE.
             - SMS: The SMS product can use the virtual number.
             - VOICE: The Voice product can use the virtual number.
          in: query
          required: false
          schema:
            type: string
            enum:
              - SMS
              - VOICE
            default: SMS
        - name: pageSize
          description: The maximum number of items to return.
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageToken
          description: 'The next pageToken value returned from a previous List request, if any.'
          in: query
          required: false
          schema:
            type: string
        - name: orderBy
          description: |-
            Supported fields for ordering by number or display_name.
          in: query
          required: false
          schema:
            type: string
      tags:
        - Active Number
  '/v1beta1/projects/{projectId}/activeNumbers/{phoneNumber}':
    patch:
      summary: Update virtual number
      description: With update virtual number, you can move a number between different SMS services and give it a new friendly name.
      operationId: NumberService_UpdateActiveNumber
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveNumber'
        '404':
          description: The active number could not be found
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 404
                      message: ''
                      status: NOT_FOUND
                      details:
                        - type: ResourceInfo
                          resourceType: sinch.unifiednumber.v1alpha2.ActiveNumber
                          resourceName: '+12025550134'
                          owner: ''
                          description: ''
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: The ID of the project.
          in: path
          required: true
          schema:
            type: string
        - name: phoneNumber
          description: Output only. The virtual number in [e.164](https://en.wikipedia.org/wiki/E.164) format with leading +. Example +12025550134.
          in: path
          required: true
          schema:
            type: string
        - name: updateMask
          description: |-
            FieldMask that determines which resource fields are modified in an update. The following fields can be updated:
            * displayName
            * smsConfiguration.servicePlanId.
          in: query
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
            default: 
              - displayName
              - smsConfiguration.servicePlanId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiveNumber'
        description: The number body to be updated
        required: true
      tags:
        - Active Number
    get:
      summary: Get a virtual number
      operationId: NumberService_GetActiveNumber
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveNumber'
        '404':
          description: The active virtual number could not be found.
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 404
                      message: ''
                      status: NOT_FOUND
                      details:
                        - type: ResourceInfo
                          resourceType: sinch.unifiednumber.v1alpha2.ActiveNumber
                          resourceName: '+12025550134'
                          owner: ''
                          description: ''
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: phoneNumber
          description: The id of the active number to retrieve.
          in: path
          required: true
          schema:
            type: string
      tags:
        - Active Number
  '/v1beta1/projects/{projectId}/activeNumbers/{phoneNumber}:release':
    post:
      summary: Release a virtual number from the project.
      description: Cancel your subscription for a specific virtual number.
      operationId: NumberService_ReleaseNumber
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveNumber'
        '404':
          description: The active virtual number could not be found.
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 404
                      message: ''
                      status: NOT_FOUND
                      details:
                        - type: ResourceInfo
                          resourceType: sinch.unifiednumber.v1alpha2.ActiveNumber
                          resourceName: '+12025550134'
                          owner: ''
                          description: ''
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: The ID of the project. Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: phoneNumber
          description: The active virtual number to release.
          in: path
          required: true
          schema:
            type: string
      tags:
        - Active Number
  '/v1beta1/projects/{projectId}/availableNumbers':
    get:
      summary: Search virtual numbers
      description: Search for virtual numbers that are available for you to activate. You can filter by any property on the available virtual number resource.
      operationId: NumberService_ListAvailableNumbers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAvailableNumbersResponse'
        '400':
          description: 'If the NumberPattern, type or capability is not valid'
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 400
                      message: 'parsing field "type": "XXX" is not a valid value'
                      status: INVALID_ARGUMENT
                      details: []
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: The resource name of the project id. Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: pattern
          description: Sequence of digits to search for.
          in: query
          required: false
          schema:
            type: string
        - name: searchPattern
          description: |-
            Search pattern to apply:
             - START: Virtual numbers that start with the provided sequence of digits.
             - CONTAINS: Virtual numbers that contain the sequence of digits.
             - END: Virtual numbers that end with the sequence of digits.
          in: query
          required: false
          schema:
            type: string
            enum:
              - START
              - CONTAINS
              - END
        - name: regionCode
          description: 'Only return virtual numbers for the given region code. ISO 3166-1 alpha-2 [country code](https://www.iso.org/obp/ui/#search) of the number.'
          in: query
          required: false
          schema:
            type: string
        - name: type
          description: |-
            Only return MOBILE, LOCAL or TOLL_FREE numbers.
             - MOBILE: Virtual numbers that belong to a specific range.
             - LOCAL: Virtual numbers that are assigned to a specific geographic region.
             - TOLL_FREE: Virtual number that is billed for all arriving calls.
          in: query
          required: false
          schema:
            type: string
            enum:
              - MOBILE
              - LOCAL
              - TOLL_FREE
            default: MOBILE
        - name: capability
          description: |-
            Filter by SMS and/or VOICE.
             - SMS: The SMS product can use the virtual number.
             - VOICE: The Voice product can use the virtual number.
          in: query
          required: false
          schema:
            type: string
            enum:
              - SMS
              - VOICE
            default: SMS
        - name: size
          description: Optional. The maximum number of items to return.
          in: query
          required: false
          schema:
            type: integer
            format: int32
      tags:
        - Available Number
  '/v1beta1/projects/{projectId}/availableNumbers/{phoneNumber}':
    get:
      summary: Fetch an available virtual number.
      description: Returns an available virtual number.
      operationId: NumberService_GetAvailableNumber
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableNumber'
        '404':
          description: The available virtual number could not be found.
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 404
                      message: ''
                      status: NOT_FOUND
                      details:
                        - type: ResourceInfo
                          resourceType: sinch.unifiednumber.v1alpha2.AvailableNumber
                          resourceName: '+12025550134'
                          owner: ''
                          description: ''
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: phoneNumber
          description: The virtual number in [e.164](https://en.wikipedia.org/wiki/E.164) format with leading +. Example +12025550134.
          in: path
          required: true
          schema:
            type: string
      tags:
        - Available Number
  '/v1beta1/projects/{projectId}/availableNumbers/{phoneNumber}:rent':
    post:
      summary: Activate a new virtual number
      description: Activate a new virtual number to use with SMS or Voice products.
      operationId: NumberService_RentNumber
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveNumber'
        '400':
          description: The project does not have enough credit to rent the number.
          content:
            application/json:
              schema: {}
        '404':
          description: The available virtual number could not be found.
          content:
            application/json:
              schema: {}
              examples:
                response:
                  value:
                    error:
                      code: 404
                      message: ''
                      status: NOT_FOUND
                      details:
                        - type: ResourceInfo
                          resourceType: sinch.unifiednumber.v1alpha2.AvailableNumber
                          resourceName: '+12025550134'
                          owner: ''
                          description: ''
        default:
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: projectId
          description: The ID of the project. Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          in: path
          required: true
          schema:
            type: string
        - name: phoneNumber
          description: The virtual number available to rent.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentNumberRequest'
        required: true
      tags:
        - Available Number
x-explorer-enabled: false
x-samples-languages:
  - curl
  - java
  - csharp
  - node
  - php
servers:
  - url: //numbers.api.sinch.com
components:
  schemas:
    NumberPatternSearchPattern:
      type: string
      enum:
        - START
        - CONTAINS
        - END
      description: |-
         - START: Virtual numbers that start with the provided sequence of digits.
         - CONTAINS: Virtual numbers that contain the sequence of digits.
         - END: Virtual numbers that end with the sequence of digits.
      title: Search Pattern
    protobufAny:
      type: object
      properties:
        typeUrl:
          type: string
        value:
          type: string
          format: byte
    typeMoney:
      type: object
      readOnly: true
      properties:
        currencyCode:
          type: string
          description: The 3-letter [currency code](https://www.iban.com/currency-codes) defined in ISO 4217.
        amount:
          type: string
          description: |-
            The amount in decimal form.
            For example `42.0001`.
            There are no guarantees on the precision unless
            documented by the message origin.
      title: Money
    ActiveNumber:
      type: object
      properties:
        phoneNumber:
          type: string
          description: Output only. The virtual number in [e.164](https://en.wikipedia.org/wiki/E.164) format with leading +. Example +12025550134.
          readOnly: true
        projectId:
          type: string
          description: Output only. Project id. Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
          readOnly: true
        displayName:
          type: string
          description: Optional. User supplied name for the virtual number.
        regionCode:
          type: string
          description: 'Output only. ISO 3166-1 alpha-2 [country code](https://www.iso.org/obp/ui/#search) of the number.'
          readOnly: true
        type:
          $ref: '#/components/schemas/NumberType'
          readOnly: true
        capability:
          type: array
          items:
            $ref: '#/components/schemas/NumberCapability'
          description: Output only. Which SMS and/or VOICE capabilities a virtual number supports.
          readOnly: true
        money:
          $ref: '#/components/schemas/typeMoney'
        paymentIntervalMonths:
          type: integer
          format: int32
          description: Output only. How often the recurring price is charged in months.
          readOnly: true
        nextChargeDate:
          type: string
          format: date-time
          description: Output only. The date of the next charge.
          readOnly: true
        expireAt:
          type: string
          format: date-time
          description: Output only. The timestamp when the subscription will expire if an expiration date has been set.
          readOnly: true
        smsConfiguration:
          $ref: '#/components/schemas/SmsConfiguration'
      description: The virtual number that has been bought by a customer and assigned to a project.
      title: Active Number
    AvailableNumber:
      type: object
      properties:
        phoneNumber:
          type: string
          title: The virtual number in [e.164](https://en.wikipedia.org/wiki/E.164) format with leading +. Example +12025550134.
        regionCode:
          type: string
          description: 'Output only. ISO 3166-1 alpha-2 [country code](https://www.iso.org/obp/ui/#search) of the virtual number.'
          readOnly: true
        type:
          $ref: '#/components/schemas/NumberType'
        capability:
          type: array
          items:
            $ref: '#/components/schemas/NumberCapability'
          description: Output only. Which SMS and/or VOICE capabilities the virtual number supports. 
          readOnly: true
        setupPrice:
          $ref: '#/components/schemas/typeMoney'
        monthlyPrice:
          $ref: '#/components/schemas/typeMoney'
        paymentIntervalMonths:
          type: integer
          format: int32
          description: Output only. How often the recurring price is charged in months.
          readOnly: true
        supportingDocumentationRequired:
          type: boolean
          format: boolean
          title: Output only. Whether or not supplementary documentation is required to complete purchase.
          readOnly: true
      description: The virtual numbers that are available to be purchased in the [Sinch dashboard](https://dashboard.sinch.com/) or via the public numbers API.
      title: Available Virtual Numbers
    ListActiveNumbersResponse:
      type: object
      properties:
        activeNumbers:
          type: array
          items:
            $ref: '#/components/schemas/ActiveNumber'
          description: List of virtual numbers associated to the client project specified in `ListActiveNumbers`.
        nextPageToken:
          type: string
          title: The token to be used for listing the next page.
        totalSize:
          type: integer
          format: int32
          title: 'List pagination'
      description: Response message to list your active virtual numbers.
      title: Active Numbers Response
    ListAvailableNumbersResponse:
      type: object
      properties:
        availableNumbers:
          type: array
          items:
            $ref: '#/components/schemas/AvailableNumber'
          description: List of available numbers.
      description: Response message to list available virtual numbers.
      title: Available Virtual Numbers Response
    NumberCapability:
      type: string
      enum:
        - SMS
        - VOICE
      default: SMS
      description: |2-
         - SMS: The SMS product can use the virtual number.
         - VOICE: The Voice product can use the virtual number.
      title: Capability
    NumberPattern:
      type: object
      properties:
        pattern:
          type: string
          description: Sequence of digits to search for.
        searchPattern:
          $ref: '#/components/schemas/NumberPatternSearchPattern'
      title: Search Pattern
    NumberType:
      type: string
      readOnly: true
      enum:
        - MOBILE
        - LOCAL
        - TOLL_FREE
      default: MOBILE
      description: |2-
         - MOBILE: Virtual numbers that belong to a specific range.
         - LOCAL: Virtual numbers that are assigned to a specific geographic region.
         - TOLL_FREE: Virtual number that is billed for all arriving calls.
      title: Type
    ProvisioningStatus:
      readOnly: true
      type: string
      enum:
        - WAITING
        - IN_PROGRESS
        - FAILED
      default: WAITING
      description: |2-
         - WAITING: The sms configuration has been scheduled.
         - IN_PROGRESS: The sms configuration change is in progress.
         - FAILED: The sms configuration change has failed.
      title: Provisioning Status for the SMS service
    RentNumberRequest:
      type: object
      properties:
        projectId:
          type: string
          description: The ID of the project. Your [project id](https://dashboard.sinch.com/settings/project-management) is found in your Sinch account.
        phoneNumber:
          type: string
          description: The available virtual number to rent.
        smsConfiguration:
          $ref: '#/components/schemas/SmsConfiguration'
      description: Request message for renting a virtual number.
      title: Rent Virtual Number Request
      required:
        - projectId
        - phoneNumber
    ScheduledProvisioning:
      type: object
      properties:
        servicePlanId:
          type: string
          description: Output only. Service plan of the scheduled provisioning task.
         
        status:
          $ref: '#/components/schemas/ProvisioningStatus'
          readOnly: true
        lastUpdatedTime:
          type: string
          format: date-time
          description: Output only. Timestamp when the status was last updated.
          readOnly: true
      title: Scheduled Provisioning
    SmsConfiguration:
      type: object
      properties:
        servicePlanId:
          type: string
          description: |-
            The current sms configuration for this virtual number.
            The service_plan_id can be found in the SMS APIs section of your [Sinch dashboard](dashboard.sinch.com).
        scheduledProvisioning:
          $ref: '#/components/schemas/ScheduledProvisioning'
          readOnly: true
      description: Sms configuration
      title: Sms Configuration
x-proxy-enabled: true
x-samples-enabled: true
